server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tianming-jianai/springcloud-config.git #Github上面的git仓库
          search-paths: # 搜索目录
            - springcloud-cofig
          username: tianming-jianai
          password: 1724473740zsG
        default-label: master #读取分支master
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    fetch-registry: true
    register-with-eureka: true
#服务注册到Eureka上


# 需要配置host域名映射
#  C:\Windows\System32\drivers\etc
#  127.0.0.1 config-3344.com

# 浏览器访问获取配置文件
# http://config-3344.com:3344/master/config-dev.yml