server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth: # 链路监控 下载jar:http://dl.bintray.com/openzipkin/maven/io/zipkin/java/zipkin-server/2.12.9/
    sampler:
      probability: 1 # 采样率值介于0 - 1 之间，1 表示全部采集
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver   #
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: m123

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-alias-package: com.atguigu.springcloud.entities # 所有Entity别名所在包

eureka:
  client:
    register-with-eureka: true # 表示是否将自己注册进Eureka默认true
    fetch-registry: true # 是否从Eureka 抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能和ribbon使用负载均衡
    service-url:
      #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
      defaultZone: http://eureka7001.com:7001/eureka # 单机版
  instance:
    prefer-ip-address: true
    instance-id: payment8001
