server:
  port: 7001

spring:
  application:
    name: eureka-server7001

eureka:
  instance:
    hostname: eureka7001.com # eureka 服务端的实例名称
  client:
    register-with-eureka: false # false 表示不向注册中心注册自己
    fetch-registry: false # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      # 集群指向其他eureka
      # defaultZone: http://eureka7002.com:7002/eureka/
      # 单机就是7001自己
      defaultZone: http://eureka7001.com/eureka/
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    # 关闭自我保护机制，保证服务不可用时及时剔除
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000

# 需要配置host域名映射
#  C:\Windows\System32\drivers\etc
#  127.0.0.1 eureka7001.com
#  127.0.0.1 eureka7002.com
